### ISSUE TITLE
Create GuestIdentityInterface

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/user#25]
I think we need to add an interface for the guest identity. I've encountered tasks where several different classes of users were considered guest. We now have the `final GuestIdentity` class and logic tied to that. We will not be able to get the correct result in the `isGuest()` method if we use an entity that is different from the provided `GuestIdentity`.

**Comment by samdark** [comment]
Interesting. What were the tasks?

**Comment by vjik** [comment]
@roxblnfk describe use case.

I think in order to implement this needed:
- create `GuestIdentityInterface`
- create `GuestIdentityFactoryInterface`
- create `SimpleGuestIdentityInterfaceFactory` that make `GuestIdentity`
- use `GuestIdentityFactoryInterface` in `CurrentUser` for create guest identity

In applications users can create own implementation of `GuestIdentityFactoryInterface` and `GuestIdentityInterface`.
